// Generated by gencpp from file rrt_implement/collision_detectionResponse.msg
// DO NOT EDIT!


#ifndef RRT_IMPLEMENT_MESSAGE_COLLISION_DETECTIONRESPONSE_H
#define RRT_IMPLEMENT_MESSAGE_COLLISION_DETECTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rrt_implement
{
template <class ContainerAllocator>
struct collision_detectionResponse_
{
  typedef collision_detectionResponse_<ContainerAllocator> Type;

  collision_detectionResponse_()
    : collision(false)  {
    }
  collision_detectionResponse_(const ContainerAllocator& _alloc)
    : collision(false)  {
  (void)_alloc;
    }



   typedef uint8_t _collision_type;
  _collision_type collision;





  typedef boost::shared_ptr< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct collision_detectionResponse_

typedef ::rrt_implement::collision_detectionResponse_<std::allocator<void> > collision_detectionResponse;

typedef boost::shared_ptr< ::rrt_implement::collision_detectionResponse > collision_detectionResponsePtr;
typedef boost::shared_ptr< ::rrt_implement::collision_detectionResponse const> collision_detectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rrt_implement::collision_detectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rrt_implement

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'rrt_implement': ['/home/lesley/ros-practice/summer/src/rrt_implement/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec9653804a13642f770edbe4a85843b2";
  }

  static const char* value(const ::rrt_implement::collision_detectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec9653804a13642fULL;
  static const uint64_t static_value2 = 0x770edbe4a85843b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rrt_implement/collision_detectionResponse";
  }

  static const char* value(const ::rrt_implement::collision_detectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool collision\n\
\n\
";
  }

  static const char* value(const ::rrt_implement::collision_detectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.collision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct collision_detectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rrt_implement::collision_detectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rrt_implement::collision_detectionResponse_<ContainerAllocator>& v)
  {
    s << indent << "collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.collision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RRT_IMPLEMENT_MESSAGE_COLLISION_DETECTIONRESPONSE_H
