// Generated by gencpp from file rrt_implement/collision_detectionRequest.msg
// DO NOT EDIT!


#ifndef RRT_IMPLEMENT_MESSAGE_COLLISION_DETECTIONREQUEST_H
#define RRT_IMPLEMENT_MESSAGE_COLLISION_DETECTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rrt_implement/world.h>
#include <rrt_implement/position.h>

namespace rrt_implement
{
template <class ContainerAllocator>
struct collision_detectionRequest_
{
  typedef collision_detectionRequest_<ContainerAllocator> Type;

  collision_detectionRequest_()
    : environment()
    , current_position()  {
    }
  collision_detectionRequest_(const ContainerAllocator& _alloc)
    : environment(_alloc)
    , current_position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::rrt_implement::world_<ContainerAllocator>  _environment_type;
  _environment_type environment;

   typedef  ::rrt_implement::position_<ContainerAllocator>  _current_position_type;
  _current_position_type current_position;





  typedef boost::shared_ptr< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct collision_detectionRequest_

typedef ::rrt_implement::collision_detectionRequest_<std::allocator<void> > collision_detectionRequest;

typedef boost::shared_ptr< ::rrt_implement::collision_detectionRequest > collision_detectionRequestPtr;
typedef boost::shared_ptr< ::rrt_implement::collision_detectionRequest const> collision_detectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rrt_implement::collision_detectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rrt_implement

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'rrt_implement': ['/home/lesley/ros-practice/summer/src/rrt_implement/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b5342966dca00135da1c816a83553ec";
  }

  static const char* value(const ::rrt_implement::collision_detectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b5342966dca0013ULL;
  static const uint64_t static_value2 = 0x5da1c816a83553ecULL;
};

template<class ContainerAllocator>
struct DataType< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rrt_implement/collision_detectionRequest";
  }

  static const char* value(const ::rrt_implement::collision_detectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "world environment\n\
position current_position\n\
\n\
================================================================================\n\
MSG: rrt_implement/world\n\
ellipsoid arena\n\
# ellipsoid[] arena_collision\n\
ellipsoid[] obstacles\n\
int64 obstacle_size\n\
ellipsoid robot\n\
================================================================================\n\
MSG: rrt_implement/ellipsoid\n\
float64[] semi_axes\n\
float64[] center\n\
#float64 epsilon\n\
float64 angle\n\
================================================================================\n\
MSG: rrt_implement/position\n\
float64 x\n\
float64 y\n\
float64 phi\n\
";
  }

  static const char* value(const ::rrt_implement::collision_detectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.environment);
      stream.next(m.current_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct collision_detectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rrt_implement::collision_detectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rrt_implement::collision_detectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "environment: ";
    s << std::endl;
    Printer< ::rrt_implement::world_<ContainerAllocator> >::stream(s, indent + "  ", v.environment);
    s << indent << "current_position: ";
    s << std::endl;
    Printer< ::rrt_implement::position_<ContainerAllocator> >::stream(s, indent + "  ", v.current_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RRT_IMPLEMENT_MESSAGE_COLLISION_DETECTIONREQUEST_H
