// Generated by gencpp from file rrt_implement/collision_detection.msg
// DO NOT EDIT!


#ifndef RRT_IMPLEMENT_MESSAGE_COLLISION_DETECTION_H
#define RRT_IMPLEMENT_MESSAGE_COLLISION_DETECTION_H

#include <ros/service_traits.h>


#include <rrt_implement/collision_detectionRequest.h>
#include <rrt_implement/collision_detectionResponse.h>


namespace rrt_implement
{

struct collision_detection
{

typedef collision_detectionRequest Request;
typedef collision_detectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct collision_detection
} // namespace rrt_implement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rrt_implement::collision_detection > {
  static const char* value()
  {
    return "7a8ffe0954973d5bc5a5648dae312862";
  }

  static const char* value(const ::rrt_implement::collision_detection&) { return value(); }
};

template<>
struct DataType< ::rrt_implement::collision_detection > {
  static const char* value()
  {
    return "rrt_implement/collision_detection";
  }

  static const char* value(const ::rrt_implement::collision_detection&) { return value(); }
};


// service_traits::MD5Sum< ::rrt_implement::collision_detectionRequest> should match 
// service_traits::MD5Sum< ::rrt_implement::collision_detection > 
template<>
struct MD5Sum< ::rrt_implement::collision_detectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rrt_implement::collision_detection >::value();
  }
  static const char* value(const ::rrt_implement::collision_detectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rrt_implement::collision_detectionRequest> should match 
// service_traits::DataType< ::rrt_implement::collision_detection > 
template<>
struct DataType< ::rrt_implement::collision_detectionRequest>
{
  static const char* value()
  {
    return DataType< ::rrt_implement::collision_detection >::value();
  }
  static const char* value(const ::rrt_implement::collision_detectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rrt_implement::collision_detectionResponse> should match 
// service_traits::MD5Sum< ::rrt_implement::collision_detection > 
template<>
struct MD5Sum< ::rrt_implement::collision_detectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rrt_implement::collision_detection >::value();
  }
  static const char* value(const ::rrt_implement::collision_detectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rrt_implement::collision_detectionResponse> should match 
// service_traits::DataType< ::rrt_implement::collision_detection > 
template<>
struct DataType< ::rrt_implement::collision_detectionResponse>
{
  static const char* value()
  {
    return DataType< ::rrt_implement::collision_detection >::value();
  }
  static const char* value(const ::rrt_implement::collision_detectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RRT_IMPLEMENT_MESSAGE_COLLISION_DETECTION_H
