// Generated by gencpp from file rrt_implement/ellipsoid_pointsRequest.msg
// DO NOT EDIT!


#ifndef RRT_IMPLEMENT_MESSAGE_ELLIPSOID_POINTSREQUEST_H
#define RRT_IMPLEMENT_MESSAGE_ELLIPSOID_POINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rrt_implement/ellipsoid.h>

namespace rrt_implement
{
template <class ContainerAllocator>
struct ellipsoid_pointsRequest_
{
  typedef ellipsoid_pointsRequest_<ContainerAllocator> Type;

  ellipsoid_pointsRequest_()
    : ellipsoid()
    , steps(0.0)  {
    }
  ellipsoid_pointsRequest_(const ContainerAllocator& _alloc)
    : ellipsoid(_alloc)
    , steps(0.0)  {
  (void)_alloc;
    }



   typedef  ::rrt_implement::ellipsoid_<ContainerAllocator>  _ellipsoid_type;
  _ellipsoid_type ellipsoid;

   typedef double _steps_type;
  _steps_type steps;





  typedef boost::shared_ptr< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ellipsoid_pointsRequest_

typedef ::rrt_implement::ellipsoid_pointsRequest_<std::allocator<void> > ellipsoid_pointsRequest;

typedef boost::shared_ptr< ::rrt_implement::ellipsoid_pointsRequest > ellipsoid_pointsRequestPtr;
typedef boost::shared_ptr< ::rrt_implement::ellipsoid_pointsRequest const> ellipsoid_pointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rrt_implement

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'rrt_implement': ['/home/lesley/ros-practice/summer/src/rrt_implement/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "635c06d23f1dcd186dfe01aa6a884ee3";
  }

  static const char* value(const ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x635c06d23f1dcd18ULL;
  static const uint64_t static_value2 = 0x6dfe01aa6a884ee3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rrt_implement/ellipsoid_pointsRequest";
  }

  static const char* value(const ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ellipsoid ellipsoid\n\
float64 steps\n\
\n\
================================================================================\n\
MSG: rrt_implement/ellipsoid\n\
float64[] semi_axes\n\
float64[] center\n\
float64 epsilon\n\
float64 angle\n\
";
  }

  static const char* value(const ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ellipsoid);
      stream.next(m.steps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ellipsoid_pointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rrt_implement::ellipsoid_pointsRequest_<ContainerAllocator>& v)
  {
    s << indent << "ellipsoid: ";
    s << std::endl;
    Printer< ::rrt_implement::ellipsoid_<ContainerAllocator> >::stream(s, indent + "  ", v.ellipsoid);
    s << indent << "steps: ";
    Printer<double>::stream(s, indent + "  ", v.steps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RRT_IMPLEMENT_MESSAGE_ELLIPSOID_POINTSREQUEST_H
