// Generated by gencpp from file rrt_implement/ellipsoid_points.msg
// DO NOT EDIT!


#ifndef RRT_IMPLEMENT_MESSAGE_ELLIPSOID_POINTS_H
#define RRT_IMPLEMENT_MESSAGE_ELLIPSOID_POINTS_H

#include <ros/service_traits.h>


#include <rrt_implement/ellipsoid_pointsRequest.h>
#include <rrt_implement/ellipsoid_pointsResponse.h>


namespace rrt_implement
{

struct ellipsoid_points
{

typedef ellipsoid_pointsRequest Request;
typedef ellipsoid_pointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ellipsoid_points
} // namespace rrt_implement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rrt_implement::ellipsoid_points > {
  static const char* value()
  {
    return "bee9a973404d35e998c420bbec7a372f";
  }

  static const char* value(const ::rrt_implement::ellipsoid_points&) { return value(); }
};

template<>
struct DataType< ::rrt_implement::ellipsoid_points > {
  static const char* value()
  {
    return "rrt_implement/ellipsoid_points";
  }

  static const char* value(const ::rrt_implement::ellipsoid_points&) { return value(); }
};


// service_traits::MD5Sum< ::rrt_implement::ellipsoid_pointsRequest> should match 
// service_traits::MD5Sum< ::rrt_implement::ellipsoid_points > 
template<>
struct MD5Sum< ::rrt_implement::ellipsoid_pointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rrt_implement::ellipsoid_points >::value();
  }
  static const char* value(const ::rrt_implement::ellipsoid_pointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rrt_implement::ellipsoid_pointsRequest> should match 
// service_traits::DataType< ::rrt_implement::ellipsoid_points > 
template<>
struct DataType< ::rrt_implement::ellipsoid_pointsRequest>
{
  static const char* value()
  {
    return DataType< ::rrt_implement::ellipsoid_points >::value();
  }
  static const char* value(const ::rrt_implement::ellipsoid_pointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rrt_implement::ellipsoid_pointsResponse> should match 
// service_traits::MD5Sum< ::rrt_implement::ellipsoid_points > 
template<>
struct MD5Sum< ::rrt_implement::ellipsoid_pointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rrt_implement::ellipsoid_points >::value();
  }
  static const char* value(const ::rrt_implement::ellipsoid_pointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rrt_implement::ellipsoid_pointsResponse> should match 
// service_traits::DataType< ::rrt_implement::ellipsoid_points > 
template<>
struct DataType< ::rrt_implement::ellipsoid_pointsResponse>
{
  static const char* value()
  {
    return DataType< ::rrt_implement::ellipsoid_points >::value();
  }
  static const char* value(const ::rrt_implement::ellipsoid_pointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RRT_IMPLEMENT_MESSAGE_ELLIPSOID_POINTS_H
