// Generated by gencpp from file rrt_implement/world.msg
// DO NOT EDIT!


#ifndef RRT_IMPLEMENT_MESSAGE_WORLD_H
#define RRT_IMPLEMENT_MESSAGE_WORLD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rrt_implement/ellipsoid.h>
#include <rrt_implement/ellipsoid.h>
#include <rrt_implement/ellipsoid.h>

namespace rrt_implement
{
template <class ContainerAllocator>
struct world_
{
  typedef world_<ContainerAllocator> Type;

  world_()
    : arena()
    , obstacles()
    , obstacle_size(0)
    , robot()  {
    }
  world_(const ContainerAllocator& _alloc)
    : arena(_alloc)
    , obstacles(_alloc)
    , obstacle_size(0)
    , robot(_alloc)  {
  (void)_alloc;
    }



   typedef  ::rrt_implement::ellipsoid_<ContainerAllocator>  _arena_type;
  _arena_type arena;

   typedef std::vector< ::rrt_implement::ellipsoid_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rrt_implement::ellipsoid_<ContainerAllocator> >::other >  _obstacles_type;
  _obstacles_type obstacles;

   typedef int64_t _obstacle_size_type;
  _obstacle_size_type obstacle_size;

   typedef  ::rrt_implement::ellipsoid_<ContainerAllocator>  _robot_type;
  _robot_type robot;





  typedef boost::shared_ptr< ::rrt_implement::world_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rrt_implement::world_<ContainerAllocator> const> ConstPtr;

}; // struct world_

typedef ::rrt_implement::world_<std::allocator<void> > world;

typedef boost::shared_ptr< ::rrt_implement::world > worldPtr;
typedef boost::shared_ptr< ::rrt_implement::world const> worldConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rrt_implement::world_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rrt_implement::world_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rrt_implement

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'rrt_implement': ['/home/lesley/ros-practice/summer/src/rrt_implement/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rrt_implement::world_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rrt_implement::world_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rrt_implement::world_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rrt_implement::world_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrt_implement::world_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrt_implement::world_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rrt_implement::world_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a3d9b4c4eef5be7211ac744e599a2a7";
  }

  static const char* value(const ::rrt_implement::world_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a3d9b4c4eef5be7ULL;
  static const uint64_t static_value2 = 0x211ac744e599a2a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::rrt_implement::world_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rrt_implement/world";
  }

  static const char* value(const ::rrt_implement::world_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rrt_implement::world_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ellipsoid arena\n\
# ellipsoid[] arena_collision\n\
ellipsoid[] obstacles\n\
int64 obstacle_size\n\
ellipsoid robot\n\
================================================================================\n\
MSG: rrt_implement/ellipsoid\n\
float64[] semi_axes\n\
float64[] center\n\
float64 epsilon\n\
float64 angle\n\
";
  }

  static const char* value(const ::rrt_implement::world_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rrt_implement::world_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arena);
      stream.next(m.obstacles);
      stream.next(m.obstacle_size);
      stream.next(m.robot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct world_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rrt_implement::world_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rrt_implement::world_<ContainerAllocator>& v)
  {
    s << indent << "arena: ";
    s << std::endl;
    Printer< ::rrt_implement::ellipsoid_<ContainerAllocator> >::stream(s, indent + "  ", v.arena);
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rrt_implement::ellipsoid_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
    s << indent << "obstacle_size: ";
    Printer<int64_t>::stream(s, indent + "  ", v.obstacle_size);
    s << indent << "robot: ";
    s << std::endl;
    Printer< ::rrt_implement::ellipsoid_<ContainerAllocator> >::stream(s, indent + "  ", v.robot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RRT_IMPLEMENT_MESSAGE_WORLD_H
